### ISSUE TITLE
Adding pasted input to workflow test yaml

### ISSUE THREAD

**Issue by malloryfreeberg** [galaxyproject/galaxy#10415]
Story: As someone building workflow tests, I would like to be able to add pasted text as an input to the workflow-test.yml so that tutorials with pasted text can be kept up-to-date using a test.

For example, the [Understanding barcodes tutorial](https://training.galaxyproject.org/training-material/topics/transcriptomics/tutorials/scrna-umis/tutorial.html) has an input which is 4 lines of text (IDs) that is pasted into the data upload tool to add as a dataset in the history. To write a [test for the a workflow](https://training.galaxyproject.org/training-material/topics/contributing/tutorials/create-new-tutorial-technical/tutorial.html#testing-the-workflow-recommended) for this tutorial, there is currently no way to add the pasted text as an input. One solution would be to create a Zenodo entry for the pasted text; however, for very small text with no real meaning (e.g. 4 lines of IDs) it seems a bit overkill to create an accessioned Zenodo object. It would be great if there was a way to include a block of small text in the workflow-test.yml file.

The following example shows how adding pasted text input to a workflow-test.yml doesn't fit the current schema:

```
---
- doc: Test sample data for a workflow
  job:
    an_input_file:
      class: File
      location: <Zenodo url>
      filetype: fastqsanger.gz
    input_pasted_text:
      class: ?
      location: ?
      filetype: tabular
  outputs:
    output:
      asserts:
        has_text:
          text: 'sometext'
```
