### ISSUE TITLE
Tool names mask each other in admin panel if installed from different toolsheds

### ISSUE THREAD

**Issue by pvanheus** [galaxyproject/galaxy#12335]
**Describe the bug**
When two tools with the same name get installed (but from different toolsheds) into a Galaxy server, the one ends up "masking" the other in the admin user interface. See below

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 21.01
Commit: (run `git rev-parse HEAD` if you run this Galaxy server)

**To Reproduce**
1. Install two tools with the same name but from different toolsheds. E.g. trimmomatic from main and testtoolshed
2. Go to Admin panel and select Install and Uninstall
3. Select Installed tools
4. Search for the tool - trimmomatic in this example
5. You see only one of the tools (with its lineage) listed. See screenshot below

**Expected behavior**
Best to show that there are two tools with the same name but different lineages (and different toolshed sources) installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/4154788/129026776-878b0a65-407f-4ac6-bec8-6ee8da2ce151.png)

**Additional context**
Ephemeris get-tool-list shows these two copies of the tool:

```
- name: trimmomatic
  owner: pjbriggs
  revisions:
  - 79f875f98770
  tool_panel_section_label: NGS Quality Control
  tool_shed_url: testtoolshed.g2.bx.psu.edu
- name: trimmomatic
  owner: pjbriggs
  revisions:
  - 51b771646466
  tool_panel_section_label: NGS Quality Control
  tool_shed_url: toolshed.g2.bx.psu.edu
```

I actually noticed the problem because I opened a workflow that uses the *main toolshed* version of trimmomatic 0.38.1 and the workflow editor switched it to version 0.36 (the version installed from main toolshed) while the Galaxy server shows 0.38.1 installed (but this was 0.38.1 from testtoolshed).

After uninstalling the `trimmomatic` that had been installed from the testtoolshed, the two versions of trimmomatic installed via main toolshed showed up:

![image](https://user-images.githubusercontent.com/4154788/129036918-bdb952c8-a184-4532-b3f8-e466be0ce142.png)
