### ISSUE TITLE
Error running singularity jobs on pulsar if the container exists in galaxy's container cache

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#13548]
**Describe the bug**
Not sure if this is a bug - I could be missing some configuration.
I'm having difficulty running jobs on pulsar with singularity. If the container does not exist in galaxy's container cache, pulsar pulls the container and the job succeeds. If the container does exist in galaxy's container cache, the command will be built to expect it to exist at the same path on the pulsar machine, so the job fails. This is my destination:
```
pulsar_destination:
    runner: pulsar_au_01  # using galaxy.jobs.runners.pulsar:PulsarMQJobRunner
    jobs_directory: /mnt/pulsar/files/staging
    transport: curl
    remote_metadata: 'false'
    default_file_action: remote_transfer
    rewrite_parameters: 'true'
    persistence_directory: /mnt/pulsar/files/persisted_data
    singularity_enabled: True
    singularity_volumes: '$job_directory:ro,$tool_directory:ro,$job_directory/outputs:rw,$working_directory:rw'
    singularity_default_container_id: '/cvmfs/singularity.galaxyproject.org/all/python:3.8.3'
    dependency_resolution: 'none'
```
**Galaxy Version and/or server at which you observed the bug**
Galaxy Australia dev server, release 21.09

**Desired behavior**
A tool command built for a remote pulsar will not contain the path to the local singularity cache.

**Comment by bernt-matthias** [comment]
How does your container resolver config look like?

Don't know anything about pulsar. Is this supposed to copy the image to the compute node?

**Comment by cat-bro** [comment]
Hi @bernt-matthias , pulsar pulls the container independently.  Nate helped me fix this.  In a description of a destination (aka environment) in the job configuration file, there a multiple galaxy config values that can be overridden including container resolvers config. The container resolvers config needs to be overridden for pulsar destinations, otherwise the job scripts will include the path to the singularity cache on galaxy, that does not exist on pulsar.

e.g.

```
    pulsar-mel2:
      runner: pulsar_mel2_runner
      tmp_dir: True
      default_file_action: remote_transfer
      outputs_to_working_directory: false
      dependency_resolution: remote
      jobs_directory: /mnt/pulsar/files/staging
      persistence_directory: /mnt/pulsar/files/persisted_data
      remote_metadata: false
      rewrite_parameters: true
      transport: curl
      singularity_enabled: false
      singularity_volumes: '{{ pulsar_singularity_volumes }}'
      singularity_default_container_id: '{{ singularity_default_container_id }}'
      container_resolvers: 
        - type: explicit_singularity
        - type: mulled_singularity
 ```
