### ISSUE TITLE
Subsequent resubmissions lose destination's resubmissions definitions, breaking subsequent resubmissions on the same destination

### ISSUE THREAD

**Issue by pcm32** [galaxyproject/galaxy#15208]
**Describe the bug**

When a destination sets itself as the resubmission destination, this resubmission gets lost on the first resubmission, disabling subsequent resubmissions. This information is lost on the various resubmissions assignments here:

https://github.com/galaxyproject/galaxy/blob/35bf24a15d271ac0db93741b594e9060549a2abb/lib/galaxy/jobs/runners/state_handlers/resubmit.py#L70-L89

The above treatment doesn't happen of course on first submission, which explains why the first resubmission works.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 22.05
Commit: 3b068eecb9f9573a90b51f3eeb1bc06d1d6eb88d

**To Reproduce**
1. Setup a tvp as done [here](https://github.com/galaxyproject/total-perspective-vortex/issues/65#issuecomment-1348619502)
2. Send a job which will fail due to memory needs.
3. See the logs, you will see one resubmission go through, but not a second one.

**Expected behavior**

Subsequent resubmissions (in this case with escalating memory allowance) should occur.

**Additional context**

I have seen subsequent resubmissions work, when the destination gets subsequently changed. Here we are trying subsequent resubmissions on the same destination.

https://github.com/galaxyproject/total-perspective-vortex/issues/65

**Comment by pcm32** [comment]
I have tried removing various pieces of the L70 - L89 quoted above, but it either breaks with exceptions or it doesn't work at all. I wonder if the resubmission state handler could just do the minimal work so that the normal handler then resolves dynamic destinations and others as if it was a first submission. The issue here I think is that the resubmit is doing stuff differently to the original handler in terms of dealing with destinations.

**Comment by bernt-matthias** [comment]
Xref https://github.com/galaxyproject/galaxy/pull/9747

I think the best would be to have a test case in the first place. To show how it should work. Some fragments are in the linked PR.

As far as I remember I played around with the caching in the last line of the linked code fragment.

My impression was that the main reason is here

https://github.com/galaxyproject/galaxy/blob/737775f586c5ab4c4cef4f486dd8826a978ed6b1/lib/galaxy/jobs/handler.py#L215

(not sure if the code fragment is still valid)

**Comment by pcm32** [comment]
I can confirm that when using independent destinations to hop on from resubmission to resubmission this works. For instance:

```
execution:
  default: tpv_dispatcher
  environments:
    extra_mem_1:
      container_monitor: false
      docker_default_container_id: quay.io/galaxyproject/galaxy-min:22.05
      docker_enabled: true
      limits_cpu: 1
      limits_memory: 7Gi
      requests_cpu: 1
      requests_memory: 7Gi
      resubmit:
      - condition: memory_limit_reached and attempt <= 4
        destination: extra_mem_2
      - condition: any_failure and attempt <= 2
        destination: tpv_dispatcher
      runner: k8s
    extra_mem_2:
      container_monitor: false
      docker_default_container_id: quay.io/galaxyproject/galaxy-min:22.05
      docker_enabled: true
      limits_cpu: 1
      limits_memory: 10Gi
      requests_cpu: 1
      requests_memory: 10Gi
      resubmit:
      - condition: memory_limit_reached and attempt <= 4
        destination: extra_mem_3
      - condition: any_failure and attempt <= 2
        destination: tpv_dispatcher
      runner: k8s
    extra_mem_3:
  default: tpv_dispatcher
  environments:
    extra_mem_1:
      container_monitor: false
      docker_default_container_id: quay.io/galaxyproject/galaxy-min:22.05
      docker_enabled: true
      limits_cpu: 1
      limits_memory: 7Gi
      requests_cpu: 1
      requests_memory: 7Gi
      resubmit:
      - condition: memory_limit_reached and attempt <= 4
        destination: extra_mem_2
      - condition: any_failure and attempt <= 2
        destination: tpv_dispatcher
      runner: k8s
    extra_mem_2:
      container_monitor: false
      docker_default_container_id: quay.io/galaxyproject/galaxy-min:22.05
      docker_enabled: true
      limits_cpu: 1
      limits_memory: 10Gi
      requests_cpu: 1
      requests_memory: 10Gi
      resubmit:
      - condition: memory_limit_reached and attempt <= 4
        destination: extra_mem_3
      - condition: any_failure and attempt <= 2
        destination: tpv_dispatcher
      runner: k8s
    extra_mem_3:
      container_monitor: false
      docker_default_container_id: quay.io/galaxyproject/galaxy-min:22.05
      docker_enabled: true
      limits_cpu: 1
      limits_memory: 12Gi
      requests_cpu: 1
      requests_memory: 12Gi
      resubmit:
      - condition: any_failure and attempt <= 2
        destination: tpv_dispatcher
      runner: k8s
    k8s:
      runner: k8s
    local:
      runner: local
    tpv_dispatcher:
      container_monitor: false
      docker_default_container_id: 'quay.io/galaxyproject/galaxy-min:22.05'
      docker_enabled: true
      function: map_tool_to_destination
      rules_module: tpv.rules
      runner: dynamic
      tpv_config_files:
      - https://raw.githubusercontent.com/galaxyproject/tpv-shared-database/main/tools.yml
      - lib/galaxy/jobs/rules/tpv_rules_local.yml
      - /galaxy/server/config/persist-seq-extra-tpv.yaml
      type: python
```

so there it starts with tpv dispatcher, but then goes on and on through the `extra_mem_*` destinations/environments. I tried though a similar approach with two tpv environments (1 and 2, so that they would do the resubmit on each other), but didn't work. I wonder if the issue might be with the fact that they might be dynamic or not.
