### ISSUE TITLE
Singularity jobs fail on first run waiting for image pull

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#15641]
**Describe the bug**
I'm sure this has been noticed before, but I could not find an issue for it.

When singularity-enabled tools run for the first time they fail waiting for the image pull from biocontainers, with an obscure error:

```
FATAL:   Unable to handle docker://quay.io/biocontainers/gtdbtk:2.2.2--pyhdfd78af_0 uri: unable to create tmp file: open /mnt/singularity_data/tmp/sbuild-tmp-cache-171554111: no such file or directory
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: usegalaxy.org.au
Commit: 22.05

**To Reproduce**
1. Install a new tool to use the singularity runner (or delete the image for an existing one)
2. Try to run the tool for the first time 

**Expected behavior**
The tool should work first time following install or update. I couldn't locate the code that throws `unable to create tmp file` but at this point I would expect the code to wait until the image pull has completed.

**Comment by bernt-matthias** [comment]
How are your container resolvers configured?

**Comment by bernt-matthias** [comment]
And, do you have a bit more context from the logs?

**Comment by cat-bro** [comment]
Hi @bernt-matthias, I'm pasting our container resolvers configuration. This happens for both mulled and explicit singularity containers.

```
    container_resolvers:
      - type: explicit
      - type: cached_explicit_singularity
        cache_directory: "{{ galaxy_tools_indices_dir }}/cache/singularity"
      - type: explicit_singularity
        cache_directory: "{{ galaxy_tools_indices_dir }}/cache/singularity"
      - type: cached_mulled_singularity
        cache_directory: "{{ galaxy_tools_indices_dir }}/cache/singularity"
      - type: mulled_singularity
        cache_directory: "{{ galaxy_tools_indices_dir }}/cache/singularity"
      - type: build_mulled_singularity
        cache_directory: "{{ galaxy_tools_indices_dir }}/cache/singularity"
        auto_install: false
```
