### ISSUE TITLE
Disable single tasks per config

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#15700]
Currently, we can enable celery in `galaxy.yml` but it's an all-or-nothing config.

It would be nice if Admins could configure this on a per-task basis. Something like the following would be nice.

```yaml
enable_celery_tasks: true
celery_conf:
  task_routes:
      galaxy.set_job_metadata: galaxy.external
      galaxy.fetch_data: none
```
