### ISSUE TITLE
The `auto_install` option on the `mulled_singularity` option is ignored

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#15717]
**Describe the bug**
Or I misunderstand its purpose. My understanding would be that it prevents image pulling and conversion at tool runtime, meaning that it only occurs when initiated by an admin.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.0.rc1
Commit: 4f52b745492ae2eb2ac8c8b56a225b8a3c78fb95

**To Reproduce**
1.  Set container resolvers:
    ```yaml
    galaxy:
      container_resolvers:
        - type: mulled_singularity
          auto_install: false
    ```
2.  Enable a Singularity destination in the job conf
3.  Run a tool with an existing biocontainer matching its requirements

**Expected behavior**
Images are not pulled/built at tool runtime.

**Additional context**
I verified that `auto_install` is indeed set to `False` in the resolver init, I just don't think it's actually used as a conditional for the pull.
