### ISSUE TITLE
BYOC usecase  - feature request

### ISSUE THREAD

**Issue by maikenp** [galaxyproject/galaxy#16596]
**Describe the bug**
For the BYOC and in the case of the actual end-user (read e.g. researcher) to be able to add his own HPC cluster to submit jobs to via Galaxy (e.g. via the ARC runner which is ongoing in development) it would be convenient that the user himself can add his X number of compute resources that he can use. 

The current functionality in the user_preferences_extra_config.yml is not sufficient to do this. One could have a single text type and the user could add *one* compute resource, but that is not flexible a-la:

```
distributed_arc_compute:
    description: Use distributed ARC compute resources
    inputs:
      - name: remote_arc_resources
        label: Add your remote resource url
        type: text
        required: False
```

What instead would be useful is to have something like the Address filed is currently, where there is a "+" button that the user can press on multiple times to add several addresses. 

Furthermore, from this list, I would like that the user could select one of them to be used as a default compute resource. Or let TPV select one for him. 

**Screenshots**
Example of what is possible today - but is too limited 
![Screenshot 2023-08-25 at 15 47 39](https://github.com/galaxyproject/galaxy/assets/22190352/06eced00-aa13-4ecd-939c-2944ac155277)

**Additional context**
This is in the context of the ARC runner which is in development, and the ESG project. Can surely also be useful not only for the ARC runner, but in general for the BYOC use-case of the ESG.
