### ISSUE TITLE
Per-host configuration ignored for some hostnames

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/galaxy#17664]
Relates to "per-host configuration" of Galaxy: https://github.com/galaxyproject/galaxy/pull/12328

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 23.2.1.dev0 https://dev.gvl.org.au/
Commit: 8bda304592e448510470ba94594ee64357d969c4

I am trying to set the `default_panel_view` as a `by_host` parameter. However, when I set the following in galaxy.yml on [Galaxy AU Dev](https://dev.gvl.org.au) it seems to have no effect. The tool panel loads the normal default:

```
    default_panel_view_by_host:
      proteomics.dev.gvl.org.au: proteomics
```

However, when I try to replicate the bug locally, the following seems to work fine i.e. I get `proteomics` as the default panel when I open the site on http://localhost/:

```
    default_panel_view_by_host:
      localhost: proteomics
```

So it seems like this feature works, but for some hostnames it stops working?

**Additional context**
I can confirm the same pattern with `support_url_by_host` (works locally, not on dev.gvl.org.au), so this seems to be a general issue with the `_by_host` feature and not limited to the `default_panel_view` param:

WORKS: `default_tool_panel: proteomics`
NOT WORKING: `default_tool_panel_by_host: dev.gvl.org.au`
NOT WORKING: `default_tool_panel_by_host: proteomics.dev.gvl.org.au`
NOT WORKING: `support_url_by_host: dev.gvl.org.au`
NOT WORKING: `support_url_by_host: proteomics.dev.gvl.org.au`
WORKS (local): `support_url_by_host: localhost/127.0.0.1`

**Comment by neoformit** [comment]
So I added the following lines to [galaxy/config/__init__.py#813](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/config/__init__.py#813):

```py
            for host_key, host_val in per_host.items():
                if per_host_option == 'support_url_by_host':
                    log.info(f"LOADING SUPPORT URL | host: {host}, host_key: {host_key}, host_val: {host_val}")
```

With the following galaxy.yml config:

```yml
support_url_by_host:
  'dev.gvl.org.au': https://site.usegalaxy.org.au/help
  'proteomics.dev.gvl.org.au': https://google.com 
```

And on dev.gvl.org.au this produces the following logs on request of proteomics.gvl.org.au:

```
LOADING SUPPORT URL | host: proteomics.gvl.org.au, host_key: dev.gvl.org.au, host_val: https://site.usegalaxy.org.au/help
```

Now, looking at the code in config/__init__.py, it obviously matches the first key that is a substring of `host`. 

So, when using this feature for subdomains, this won't work: 
```yml
support_url_by_host:
  'dev.gvl.org.au': https://site.usegalaxy.org.au/help
  'proteomics.dev.gvl.org.au': https://google.com 
```

... but this will:
```yml
support_url_by_host:
  'proteomics.dev.gvl.org.au': https://google.com
  'dev.gvl.org.au': https://site.usegalaxy.org.au/help 
```

I will link this from the PR so that others can see this issue. @jdavcs I'll leave it up to you whether this is a bug or a feature!
