### ISSUE TITLE
[help_wanted] File downloads failing from test S3 backends in the object store

### ISSUE THREAD

**Issue by cat-bro** [galaxyproject/galaxy#19255]
Galaxy Australia is considering adding S3 storage for some user data. The purpose would be for the storage of data that is not newly created, maybe 3+ months since last access. We have been testing several options (object store, MinIO and an AWS bucket). We are running tests of how Galaxy handles access to files that are not in the cache. We are testing running jobs on datasets that are not in the cache, and downloading datasets that are not in the cache.

Results from running jobs are excellent on the local cluster and on pulsar - the jobs end up in ‘ok’ state.

Results from downloading files are concerning. I have been testing this with file sizes of 2GB, 4GB, 6GB, 8GB and 10GB. Two of the backends we are testing (ids `minio_test` and `aws_bucket_test` in object store conf) have type `boto3` and only the downloads of 2GB and 4GB files are successfully downloaded. For anything larger, attempting to download leads to timeout (504). Dataset peek is similarly affected.

For the backend connected to openstack object storage (id `pawsey_s3_test` in our object store conf) we have used backend type `generic_s3`. The downloads appear to succeed, but for sizes 4GB and above, the downloaded files are truncated to about 3GB each. It would be preferable if it failed with a timeout as it does in the other cases.

At this point our test candidates seem unusable, especially the one in which downloaded files are truncated.

I'm not sure what the solution for this should be. If I click on the floppy disk 10 minutes after the first attempt has timed out, the file has arrived in the cache and can be downloaded, so I wonder if the user can be informed that the file is not ready and advised to try again. I also wonder if the download could be directly from the storage rather than via the cache, though this would be tricky with different data types.

I’m keen to talk to others who are using or testing S3 in the Galaxy object store.

This is a link to our [object store conf](https://github.com/usegalaxy-au/infrastructure/blob/master/templates/galaxy/config/galaxy_object_store_conf.yml.j2#L174C1-L259C47) and I've pasted the relevant entries below.

```
- id: minio_test
  weight: 0
  type: boto3
  store_by: uuid
  auth:
    access_key: {{ vault_galaxy_minio_access_key }}
    secret_key: {{ vault_galaxy_minio_secret_key }}
  bucket:
    name: galaxytest
  connection:
    endpoint_url: https://platforms-s3-poc.aarnet.edu.au
  cache:
    path: /mnt/user-data-volD/minio_test_cache
    size: 50
    cache_updated_data: true
  # transfer:   # see transfer options for boto3 above in AWS configuration.
- id: aws_bucket_test
  type: boto3
  weight: 0
  store_by: uuid
  auth:
    access_key: {{ vault_aws_galaxytest_access_key }}
    secret_key: {{ vault_aws_galaxytest_secret_key }}
  bucket:
    name: ga-s3-test-230823
  connection:  # not strictly needed but more of the API works with this.
    region: ap-southeast-2
  cache:
    path: /mnt/user-data-volD/aws_bucket_test_cache
    size: 50
    cache_updated_data: true
- id: pawsey_s3_test
  type: generic_s3
  weight: 0
  store_by: uuid
  auth:
    access_key: {{ vault_pawsey_s3_test_access_key }}
    secret_key: {{ vault_pawsey_s3_test_secret_key }}
  bucket:
    name: galaxy-test
    use_reduced_redundancy: false
    max_chunk_size: 250
  connection:
    host: "projects.pawsey.org.au"
    port: 443
    is_secure: true
    conn_path: "/"
  cache:
    path: /mnt/user-data-volD/pawsey_s3_test_cache
    size: 50
    cache_updated_data: true
```
