### ISSUE TITLE
Datasets without `object_store_id` are created in setup with labelled object stores

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#19882]
**Describe the bug**

Since more than a month I'm running a setup with labeled object stores backends (see below). I noticed that in the `datasets` table there are still datasets popping up where the object_store_id is NULL. 

The only thing that I noticed is that all of them are in state `discarded` or `paused` (almost all of them are `discarded`). 

Might be OK, but seems relevant for the setup of the cleanup scripts where one would specify the object store IDs which would make the actions ignore these datasets.

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1

**To Reproduce**

Unsure.

**Expected behavior**

No datasets without object store id are created.

**Additional context**

```yaml
  object_store_config:
    type: distributed
    search_for_missing: true
    backends:
      - id: "files-24.1"
        type: disk
        device: "files-24.1"
        weight: 1
        store_by: uuid
        allow_selection: true
        private: false
        name: "Permanent Storage"
        description: Data in Permanent Storage is not deleted automatically. Default quota is {{ galaxy_default_quota }}. Data that has been marked as deleted will be purged after {{ galaxy_maxage }} days. Histories of users that left the UFZ will be archived and purged.
        files_dir: database/files_24.1/
        badges:
          - type: not_backed_up
      - id: "files-24.1-scratch"
        type: disk
        device: "files-24.1"
        weight: 0
        store_by: uuid
        allow_selection: true
        private: true
        quota:
          source: scratch
        name: "Scratch: {{ galaxy_scratch_maxage }}-day storage"
        description: "Data in scratch storage is scheduled for automatic removal after {{ galaxy_scratch_maxage }} days. Default quota is {{ galaxy_scratch_default_quota }}."
        files_dir: database/files_24.1/
        badges:
          - type: not_backed_up
          - type: short_term
            message: "Data stored here is scheduled for removal after 30 days"
      - id: legacy
        type: disk
        store_by: id
        weight: 0
        files_dir: database/files/
```
