### ISSUE TITLE
`pg_cleanup` fails with psycopg2 exception if used with `--object-store-id`

### ISSUE THREAD

**Issue by bernt-matthias** [galaxyproject/galaxy#19880]
**Describe the bug**

During `pg_cleanup`  with `--object-store-id "files-24.1-scratch"` disk usage is recalculated with

```sql
UPDATE galaxy_user SET disk_usage = (
    WITH per_user_histories AS (
        SELECT id
        FROM history
        WHERE user_id = %(id)s
        AND NOT purged
    ),
    per_hist_hdas AS (
        SELECT DISTINCT dataset_id
        FROM history_dataset_association
        WHERE NOT purged
        AND history_id IN (SELECT id FROM per_user_histories)
    )
    SELECT COALESCE(SUM(COALESCE(dataset.total_size, dataset.file_size, 0)), 0)
    FROM dataset
    LEFT OUTER JOIN library_dataset_dataset_association ON dataset.id = library_dataset_dataset_association.dataset_id
    WHERE dataset.id IN (SELECT dataset_id FROM per_hist_hdas)
    AND library_dataset_dataset_association.id IS NULL
    AND (dataset.object_store_id NOT LIKE 'user_objects://%' OR dataset.object_store_id IS NULL)
    AND ( dataset.object_store_id IS NULL  OR  dataset.object_store_id NOT IN %(exclude_object_store_ids)s )
)
WHERE id = %(id)s
```

Called with `args={'id': 1, 'exclude_object_store_ids': ('files-24.1', 'files-24.1-scratch', 'legacy')}`

This fails with

```
  File "/gpfs1/data/galaxy_server/galaxy-dev/./scripts/cleanup_datasets/pgcleanup.py", line 1328, in _execute
    sql_str = cur.mogrify(sql, args).decode("utf-8")
              ^^^^^^^^^^^^^^^^^^^^^^
psycopg2.ProgrammingError: argument formats can't be mixed
```

**Galaxy Version and/or server at which you observed the bug**
Galaxy Version: 24.1
Commit: 4607d88509

**To Reproduce**

**Additional context**

My object store config:

```yaml
  object_store_config:
    type: distributed
    search_for_missing: true
    backends:
      - id: "files-24.1"
        type: disk
        device: "files-24.1"
        weight: 1
        store_by: uuid
        allow_selection: true
        private: false
        name: "Permanent Storage"
        description: Data in Permanent Storage is not deleted automatically. Default quota is {{ galaxy_default_quota }}. Data that has been marked as deleted will be purged after {{ galaxy_maxage }} days. Histories of users that left the UFZ will be archived and purged.
        files_dir: database/files_24.1/
        badges:
          - type: not_backed_up
      - id: "files-24.1-scratch"
        type: disk
        device: "files-24.1"
        weight: 0
        store_by: uuid
        allow_selection: true
        private: true
        quota:
          source: scratch
        name: "Scratch: {{ galaxy_scratch_maxage }}-day storage"
        description: "Data in scratch storage is scheduled for automatic removal after {{ galaxy_scratch_maxage }} days. Default quota is {{ galaxy_scratch_default_quota }}."
        files_dir: database/files_24.1/
        badges:
          - type: not_backed_up
          - type: short_term
            message: "Data stored here is scheduled for removal after 30 days"
      - id: legacy
        type: disk
        store_by: id
        weight: 0
        files_dir: database/files/
```
