### ISSUE TITLE
Enable multiple cache, job_work dirs per object-store

### ISSUE THREAD

**Issue by bgruening** [galaxyproject/galaxy#20062]
We would like to have the possibility to specify multiple cache dirs and job_work dirs per object stores.
With the support of `weight` we could do some round-robin over those dirs and suspend/replace job_work dirs more easily. Having multiple cache dirs has also a few advantages imho.

The downside I think is that Galaxy needs to "search" for the correct dir for each job, so the worst case is probably that Galaxy needs to do a `os.path.exists()` per job per X cache/job_work dir. But this could be cached maybe in python?

```
type: generic_s3
auth:
  access_key: ...
  secret_key: ...
bucket:
  name: unique_bucket_name_all_lowercase
  use_reduced_redundancy: false
  max_chunk_size: 250
connection:
  host: swift.example.org
  port: 6000
  conn_path: /
  multipart: true
cache:
  - path: database/object_store_cache_01
    size: 1000
    cache_updated_data: true
    weight: 2
  - path: database/object_store_cache_02
    size: 1000
    cache_updated_data: true
    weight: 1
extra_dirs:
  - type: job_work
    path: database/job_working_directory_01
    weight: 2
  - type: job_work
    path: database/job_working_directory_02
    weight: 1

```

**Comment by natefoo** [comment]
We store `object_store_id` on the `job` table for the distributed object store, so if the extra dirs were implemented as distributed backends with their own IDs then it wouldn't need to search. And there should be no performance penalty for the default case anyway since there would be no need to search when there is only one dir of that type.

**Comment by mvdbeek** [comment]
I assume this is triggered by some limitation you've run into, can you tell us what that is ?

**Comment by bgruening** [comment]
If hundreds of nodes are hamming on one NFS share this is not optimal. So we have multiple physical boxes, with separate network cards etc and we used to do round-robin via multiple backends (using weights for the same physical hard drive). However, this was a hack and does not work if you have now mixed, S3, NFS etc ... and it also does not work for cache storage anymore.

**Comment by cat-bro** [comment]
Galaxy Australia also has a use case for this. It would be useful to put the galaxy job working directories in a different location from those for jobs that run locally, without using separate object store backends. I have tried overriding `job_working_directory` for individual jobs using TPV but this doesn't work because jwd from the object store backend is always used.

**Comment by bgruening** [comment]
@cat-bro @natefoo would something like this work for you?

```yaml
type: distributed
global_max_percent_full: 95
search_for_missing: false
backends:
  - id: posix_fast_a
    type: disk
    name: POSIX Fast A
    description: >
      Primary shared filesystem for most jobs.
    store_by: uuid
    weight: 4
    max_percent_full: 90
    files_dir: /srv/galaxy/posix-fast-a/files
    workspaces:
      - id: local
        weight: 3
        extra_dirs:
          - type: job_work
            path: /srv/galaxy/posix-fast-a/jobs/local
          - type: temp
            path: /srv/galaxy/posix-fast-a/tmp/local
      - id: pulsar
        weight: 1
        extra_dirs:
          - type: job_work
            path: /srv/galaxy/posix-fast-a/jobs/pulsar
          - type: temp
            path: /srv/galaxy/posix-fast-a/tmp/pulsar
```

```yaml
type: boto3
id: galaxy-cache
store_by: uuid
auth:
  access_key: access_moo
  secret_key: secret_cow

bucket:
  name: unique_bucket_name_all_lowercase

workspaces:
  - id: cache_a
    weight: 2
    cache:
      path: database/object_store_cache_a
      size: 1000
      cache_updated_data: true
    extra_dirs:
      - type: job_work
        path: database/job_working_directory_shared
      - type: temp
        path: database/tmp_shared

  - id: cache_b
    weight: 1
    cache:
      path: database/object_store_cache_b
      size: 1000
      cache_updated_data: true
    extra_dirs:
      - type: job_work
        path: database/job_working_directory_shared
      - type: temp
        path: database/tmp_shared
```

`workspaces` or `temp_locations` or `scratch_locations`?
