### ISSUE TITLE
user prefs asking for optional values

### ISSUE THREAD

**Issue by martenson** [galaxyproject/galaxy#20112]
with `user_preferences_extra_conf.yml` looking like this

```
  invenio_sandbox:
      description: Your Invenio RDM _SANDBOX_ Account
      inputs:
          - name: token
            label: Personal Token to publish records to Invenio RDM
            type: secret
            store: vault
            required: False
          - name: public_name
            label: Public name to publish records (formatted as "Lastname, Firstname")
            type: text
            required: False
          - name: public_records
            label: Whether to make new draft records publicly accessible (Yes) or restricted (No).
            type: boolean
            required: False
  zenodo_sandbox:
      description: Your Zenodo _SANDBOX_ Account
      inputs:
          - name: token
            label: Personal Access Token used to create draft records and to upload files. You can manage your tokens at https://sandbox.zenodo.org/account/settings/applications/
            type: secret
            store: vault
            required: False
          - name: public_name
            label: Creator name to associate with new records (formatted as "Last name, First name"). If left blank "Anonymous Galaxy User" will be used. You can always change this by editing your record directly.
            type: text
            required: False
  zenodo:
      description: Your Zenodo Account
      inputs:
          - name: token
            label: Personal Access Token used to create draft records and to upload files. You can manage your tokens at https://zenodo.org/account/settings/applications/
            type: secret
            store: vault
            required: False
          - name: public_name
            label: Creator name to associate with new records (formatted as "Last name, First name"). If left blank "Anonymous Galaxy User" will be used. You can always change this by editing your record directly.
            type: text
            required: False

```

The interface behaves unexpectedly as demonstrated on the video:

https://github.com/user-attachments/assets/969e53e9-6b58-40eb-9100-64f134b07068

I'd expect that the interface will not prompt me for optional values.

( I also do not understand why it is prompting me one by one instead of showing me all values that it wants.)

chrome on macos
latest 24.2
