### ISSUE TITLE
Improve utility of configuration specification

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5148]
This issue a follow up to https://github.com/galaxyproject/galaxy/pull/5105 to improve what is there beyond a MVP.

- [ ] Allow more annotations of Galaxy options in config_schema.yml and use when generating documentation.
  - [ ] Specify an optional minimum Galaxy version that implements the options.
  - [ ] Specify how common it would be to modify the options - so can build a version of the docs that hides un-common options.
  - [ ] Specify unsafe / beta options and automatically warn on them.
  - [ ] Specify paths and path defaults more intelligently.
- [ ] Pre-process the options when loading into Galaxy to not need to duplicate type information like converting strings to integers when parsing ini options.
- [ ] Implement a modality of Galaxy that prevents loading non-lint passing configurations.
- [ ] Rework various other configuration files and allow them to be embedded in a hierarchal way into galaxy.yml.
  - [ ] job_conf.yml
  - [ ] per-IE options
  - [ ] datatypes
  - [ ] dependency resolvers (can already by yaml)
  - [ ] job metrics (can already by yaml)
  - [ ] containers (is already yaml)

**Comment by natefoo** [comment]
John and I worked on a specification for a YAML job configuration and came up with the following. There's some incomplete stuff in there in regards to templating but we didn't want to lose this since a fair amount of thought went in to it.

```yaml
job_config:
  runners:
    local:
      class: galaxy.jobs.runners.local:LocalJobRunner
      workers: 4
      default: true
  handling:
    default: handlers
    method:
      - uwsgi_mule_message
      - db_preassign
    processes:
      handler0:
        tags: 
          - handlers
      handler1:  # no config
  execution:
    default: local
    environments:
      # could also be a dict keyed on ID, list is used to support the templating idea
      - id: local
        runner: local
      - common:
          native_spec: '-cores $cores -mem $mem' 
          mem: 12
          runner: drmaa
        environemnts:
          - id: bigmem
            mem: 45
      # dict version
      local:
          runner: local
  tools:
    # one option for specifying mapping defaults, instead of in "handling" and "execution"
    defaults:
      environment: foo
      handler: local
    mappings:
      cat1:
        environment: bar
  tools:
    # alternative tools implementation
    cat1:
      environment: bar
```

**Comment by jmchilton** [comment]
@natefoo 

I think I want to make:

```yaml
runners:
  local:
      load: 'galaxy.jobs.runners.local:LocalJobRunner'
```

into

```yaml
running:
  workers: 4
  dynamic: {}
  runners:
    local:
      load: 'galaxy.jobs.runners.local:LocalJobRunner'
```

so it matches execution and we have a place to configure default worker count and dynamic parameters? (why continue to pretend the dynamic runner is a runner - right?). Do you recall if this was something we discussed and dismissed?

At the cost of consistency we could make either ``runners`` or ``running`` available at the top-level and just fill in defaults if ``running`` is absent but ``runners`` are not.
