### ISSUE TITLE
CWL for Command-binding of Galaxy Tools

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5905]
Most of the issues tracked for the CWL Galaxy fork [here](https://github.com/common-workflow-language/galaxy) are about evaluating arbitrary CWL tools in Galaxy - bringing CWL artifacts into the Galaxy community. If instead one considers the problem "how can Galaxy tool developers develop CWL tools and Galaxy tools at the same time" - a potentially interesting solution emerges to build blended tools that leverage the strengths of both tool languages (Galaxy for user interface development and CWL for command-line definition).

Consider the Galaxy tool:

```xml
<tool id="seqtk_seq" name="Convert to FASTA (seqtk)" version="0.1.0">
    <requirements>
        <requirement type="package" version="1.2">seqtk</requirement>
    </requirements>
    <command detect_errors="exit_code"><![CDATA[
        seqtk seq -a '$input1' > '$output1'
    ]]></command>
    <inputs>
        <param type="data" name="input1" format="fastq" />
    </inputs>
    <outputs>
        <data name="output1" format="fasta" />
    </outputs>
    <help><![CDATA[
         Convert to FASTA (seqtk)
    ]]></help>
</tool>
```

One could imagine modifying galaxy so this could be represented as a Galaxy XML tool where the "tool state" and tool interface are still compatible with Galaxy tools but the command-line binding happens in a CWL tool.

So this version of seqtk_seq.xml, where the ``tool_type="cwl_interface"` prompts Galaxy to look for a file with the same name but with a cwl extension:

```xml
<tool id="seqtk_seq" version="1.2" tool_type="cwl_interface">
    <inputs>
        <param type="data" name="input1" format="fastq" />
    </inputs>
    <outputs>
        <data name="output1" format="fasta" />
    </outputs>
</tool>
```

so when paired with:

seqtk_seq.cwl

```yaml
#!/usr/bin/env cwl-runner
cwlVersion: v1.0
class: CommandLineTool
id: "seqtk_seq"
doc: |
    Convert to FASTA (seqtk)
inputs:
  - id: input1
    type: File
    inputBinding:
      position: 1
      prefix: "-a"
outputs:
  - id: output1
    type: File
    outputBinding:
      glob: out
baseCommand: ["seqtk", "seq"]
arguments: []
stdout: out
hints:
  SoftwareRequirement:
    packages:
    - package: seqtk
      version:
      - "1.2"
```

The command block and cheetah aren't needed because CWL is used to build the command-line. Help, exit code detection, requirements are all readily inferred from the CWL. (TODO: Sketch out.)

Because the Galaxy state handling remains the same - the actual implementation of this is I think MUCH easier than what is being attempted with the CWL Galaxy fork to handle arbitrary CWL as CWL. All executions still look like Galaxy tool executions to Galaxy - only a few details around job command-line generation and such change and most of these details should be pretty close to ready to go in that branch and other work that has been started in this branch and merged into Galaxy already. Everything above the jobs layer could stay the same if we restrict our interest for now on these types of CWL tools (this includes job state, tool parameters, workflow state, the API, the entire UI of Galaxy - they all stay the same). 

The above example was very simple but I think even more complex Galaxy-ism could map nicely to CWL inputs with relatively clean markup. For instance, consider:

```xml
<inputs>
  <conditional name="reference_source">
    <param name="reference_source_selector" type="select" label="Will you select a reference genome from your history or use a built-in index?" help="Built-ins were indexed using default options. See `Indexes` section of help below">
      <option value="cached">Use a built-in genome index</option>
      <option value="history">Use a genome from history and build index</option>
    </param>
    <when value="cached">
      <param name="ref_file" type="select" label="Using reference genome" help="Select genome from the list" cwl_input_binding="ref_file" cwl_input_data_field="path">
        <options from_data_table="bwa_mem_indexes">
          <filter type="sort_by" column="2" />
          <validator type="no_options" message="No indexes are available" />
        </options>
      </param>
    </when>
    <when value="history">
      <param name="ref_file" type="data" format="fasta" label="Use the following dataset as the reference sequence" help="You can upload a FASTA sequence to the history and use it as reference" cwl_input_binding="ref_file" />
    </when>
  </conditional>
</inputs>
```

paired with a CWL including the following in its "inputs":

```yaml
  - id: ref_file
    type: File
    inputBinding:
      position: 1
      prefix: "-a"
```

Here we add ``cwl_input_binding`` to describe in Galaxy how to map an input parameter to part of the CWL job JSON and ``cwl_input_data_field`` to go a step further and pull things out of data tables when mapping to CWL. So now we have all the conditional-handling, validation, and interface logic that still works nicely in Galaxy - but the details that CWL cares about are captured in the structured CWL document. That CWL is still runnable in platforms without data tables and such and those validators and such all still work in Galaxy without having to develop CWL-isms to describe them - the best of both worlds!

Mapping conditionals to simple CWL parameters which aren't nested makes some sense in the above example. One could imagine the inverse as well - mapping multiple Galaxy parameters to complex record types in CWL:

```xml
<inputs>
  <conditional name="inputs">
    <param name="input_type" type="select">
      <option value="unpaired">Use a single unpaired input</option>
      <option value="paired">Use paired inputs</option>
    </param>
    <when value="unpaired">
      <param name="input1" type="data" cwl_input_binding="reads|in1">
    </when>
    <when value="paired">
      <param name="input1" type="data" cwl_input_binding="reads|in1">
      <param name="input2" type="data" cwl_input_binding="reads|in2">
    </when>
</inputs>
```

```yaml
  reads:
    type:
      type: record
      fields:
        in1:
          type: File
          inputBinding:
            position: 3
        in2:
          type: File?
          inputBinding:
            position: 4
```

I haven't included examples of CWL arrays or Galaxy collections or repeats, but I think a few mapping elements such as this could lead to pretty clear semantics. (TODO: this - examples of repeats, collections, and arrays).

Galaxy doesn't enable this by default, but the guts exist for Galaxy YAML files (see https://github.com/galaxyproject/galaxy/blob/dev/test/functional/tools/simple_constructs.yml for instance). So one could imagine going a step further and just using the CWL YAML document as the tool basis and embedding just the Galaxy specific stuff in a couple Galaxy vendor extensions (leveraging stuff already in Galaxy):

```yaml
#!/usr/bin/env cwl-runner
$namespaces:
  gx: "http://galaxyproject.org/cwl#"
cwlVersion: v1.0
class: CommandLineTool
id: "seqtk_seq"
gx:version: '1.2'
doc: |
    Convert to FASTA (seqtk)
inputs:
  - id: input1
    type: File
    inputBinding:
      position: 1
      prefix: "-a"
outputs:
  - id: output1
    type: File
    outputBinding:
      glob: out
baseCommand: ["seqtk", "seq"]
arguments: []
stdout: out
hints:
  gx:Interface:
    inputs:
       - <inputs, repeats, conditional, validators, etc... as YAML>
    outputs:
       - <output information not captured above>
  gx:Version: "1.2"
  SoftwareRequirement:
    packages:
    - package: seqtk
      version:
      - "1.2"
```
