### ISSUE TITLE
Performance issue in release_18.01

### ISSUE THREAD

**Issue by lecorguille** [galaxyproject/galaxy#5975]
Hi,

# Introdution
In one of our project with @Mataivic, we generate rather huge dataset collections (3 x 10000 files) easily. We had some performance issues with the 17.05 when the form rendering (to populate the drop list I guess). It could take several minutes to display a tool form which required some fasta as input (we had 30000 of them in the history)
The timing with this 18.01 was perfect because the project was stuck.

But but but, it's worse with the 18.01. I sure or at least I hope that it's because I did a mistake during the migration.

# Symptoms with this 18.01
Even with less than 6000 files in the history, Galaxy give up after 59s when displaying the tool form.
A red box appears eventually
```
Cannot connect to Galaxy
Galaxy is currently unreachable. Please try again in a few minutes. Please contact a Galaxy administrator if the problem persists.
```

With the module Web developer in Chrome, we get in network:
```
#Name: build?version=2.0.2&__identifer=5f1cbjxk366&tool_version=2.0.2
#Status: (failed)
#Type: xhr
#Initiator: jquery.js:9175
#Size: 0B
#Time: 1.0 min
```

We also reach this "timeout" when we want to display the job within the admin interface or when we want to get a shared history. 

We (myself, @mhoebekesbr and @pbordron) don't get so much info in either the uwsgi or the nginx logs. But maybe, we don't watch at the good place.
We tried to skip NGINX, and we get the same result 
```
uwsgi:
   http: :8080
```

# Context

## Hardware
It's a rather small dev instance hosted in a VM:
- 6 cores
- 12 Go RAM

### galaxy.yml
```yaml
uwsgi:
  http: :8080
  processes: 4
  threads: 4
  offload-threads: 1
  static-map: /static/style=static/style/blue
  static-map: /static=static
  master: true
  virtualenv: .venv
  pythonpath: lib
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true
  mule: lib/galaxy/main.py
  farm: job-handlers:1

```

### supervisord
```
[program:galaxy_uwsgi]
command         = /w/galaxy/galaxydev/galaxy/.venv/bin/uwsgi --yaml /w/galaxy/galaxydev/galaxy/config/galaxy.yml --logto /tmp/uwsgi_logto.log
directory       = /w/galaxy/galaxydev/galaxy/
umask           = 022
autostart       = true
autorestart     = true
startsecs       = 10
user            = galaxydev
environment     = PATH="/w/galaxy/galaxydev/galaxy/.venv/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",PYTHONPATH="/w/galaxy/galaxydev/galaxy/lib",HOME="/w/galaxy/galaxydev/galaxy/",USER="galaxydev",DRMAA_LIBRARY_PATH=/opt/sge/lib/lx24-amd64/libdrmaa.so.1.0
;numprocs        = 1
stopsignal      = INT
log_stdout      = true
log_stderr      = true
loglevel        = blather
logfile         = /tmp/supervisord_galaxy_uwsgi.log
```

### nginx
```
upstream galaxy {
    server localhost:8080;
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    client_max_body_size 10G; # max upload size that can be handled by POST requests through nginx

    # use a variable for convenience
    set $galaxy_root /w/galaxy/dev/galaxy;

    location / {
        proxy_pass          http://galaxy;
        # pour debug
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        proxy_connect_timeout 300;
        # end pour debug
        proxy_set_header    X-Forwarded-Host $host;
        proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
    }

    # serve framework static content
    location /static {
        alias $galaxy_root/static;
        expires 24h;
    }
    location /static/style {
        alias $galaxy_root/static/style/blue;
        expires 24h;
    }
    location /static/scripts {
        alias $galaxy_root/static/scripts;
        expires 24h;
    }
    location /robots.txt {
        alias $galaxy_root/static/robots.txt;
        expires 24h;
    }
    location /favicon.ico {
        alias $galaxy_root/static/favicon.ico;
        expires 24h;
    }

    # serve visualization and interactive environment plugin static content
    location ~ ^/plugins/(?<plug_type>.+?)/(?<vis_name>.+?)/static/(?<static_file>.*?)$ {
        alias $galaxy_root/config/plugins/$plug_type/$vis_name/static/$static_file;
        expires 24;
    }

    location /_x_accel_redirect/ {
        internal;
        alias /;
    }
```

# Questions:
- Since we couldn't get any informative messages, do you any advice to get some?
- Do you see any obvious mistake in our configuration?

We can provide you some extra information if those above aren't enough.

Many thanks but advance.
