### ISSUE TITLE
uWSGI threading issue

### ISSUE THREAD

**Issue by marijazmf** [galaxyproject/galaxy#6362]
Dear developers,
 
Since last Galaxy upgrade some issue with uwsgi and threading arise.
I used[ Galaxy documentation](https://docs.galaxyproject.org/en/master/admin/scaling.html ) as a guideline to configure galaxy.yml: 

```
uwsgi:
  socket: 127.0.0.1:4001
  http: 0.0.0.0:8080
  buffer-size: 16384
  processes: 4
  threads: 8
  offload-threads: 2
  static-map: /static/style=static/style/blue
  static-map: /static=static
  master: true
  virtualenv: .venv
  pythonpath: lib
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  thunder-lock: true
  die-on-term: true
  hook-master-start: unix_signal:2 gracefully_kill_them_all
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  py-call-osafterfork: true
  enable-threads: true  
  mule: lib/galaxy/main.py
  mule: lib/galaxy/main.py
  mule: lib/galaxy/main.py
  farm: job-handlers:1,2,3

```
When I run Galaxy, I got error message - **error: can't start new thread**
 
Also if I run some job which require a lot of threads, I always get error message - **RuntimeError: can't start new thread** 
I tried to increase number of processes in /etc/security/limits.conf for galaxy user but it didn’t help.
 
What can be solution? Do you have any idea what could be wrong?
 
Thanks a lot for your support.
Best,
Marija
