### ISSUE TITLE
Tool search issues

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#7039]
https://usegalaxy.eu/api/tools?q=last is not the desirable output, only results are "blast" when looking for "select last". @martenson any ideas why? Also affects main. I would have expected to see the two select last tools and maybe lastz before blast.

Filed a new issue since this is more actionable, there is a clear example of what it should be / and what it is.

cc @shiltemann 

xref https://github.com/galaxyproject/galaxy/issues/2272

**Comment by martenson** [comment]
fwiw the 'select last tool' actually has id 'tp_tail_tool' or 'Show tail1' and the help does not contain many words either, so it is understandable that search is limited. However there are things we could do I think. Mainly limit the results to unique tools and disregard their versions. It might be a bit tricky though.

Quick fix is to increase the results limit.

**Comment by hexylena** [comment]
Ok, interesting, I would have expected a different result given our boosts and limit:

```yaml
  tool_name_boost: 40
  tool_section_boost: 1
  tool_description_boost: 40
  tool_label_boost: 1
  tool_stub_boost: 1
  tool_help_boost: 1
  tool_search_limit: 80
```
(via [our galaxy vars](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/galaxy.yml#L728))

The search only returns 30 results on EU, even counting the different versions of the same tool, so I would have expected that it finds more. I'm struggling slightly to reproduce it since I can only do so in a production environment that takes 12 minutes to reload.

Edit: I was looking at the wrong URL / results limit should be fine.
