### ISSUE TITLE
Enabling watchers in multiprocess mode causes a segfault on a Mac

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/galaxy#9085]
A segmentation fault occurs consistently under the following conditions:
- enable any watcher: tours, config, tools, job_rules
- db: postgres (similar issue w/sqlite but, possibly, another cause)
- OS: macOS Mojave 10.14.5
- tested under Python: 2.7, 3.5, 3.6
- uwsgi processes: > 1 (if 1, then no issue)
- uwsgi master: true (otherwise runtime error)
- galaxy branch: dev

This *does not* happen on Linux.
The issue was first discovered by @dannon  .

The segfault is triggered on calling `observer.start()`, which leads here:
https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog/observers/fsevents.py#L137
which leads here:
https://github.com/gorakhargosh/watchdog/blob/master/src/watchdog_fsevents.c#L337

Here's the relevant traceback:

```
galaxy.web_stack INFO 2019-12-09 21:44:22,018 [p:4189,w:1,m:0] [MainThread] Galaxy server instance 'main.web.1' is running
Starting server in PID 4189.
serving on http://127.0.0.1:8080
galaxy.web_stack INFO 2019-12-09 21:44:22,028 [p:4196,w:2,m:0] [MainThread] Galaxy server instance 'main.web.2' is running
galaxy.model.database_heartbeat DEBUG 2019-12-09 21:44:22,056 [p:4189,w:1,m:0] [database_heartbeart_main.web.1.thread] main.web.1 is config watcher
galaxy.util.watcher DEBUG 2019-12-09 21:44:22,060 [p:4189,w:1,m:0] [database_heartbeart_main.web.1.thread] Watching for changes in directory: /Users/sergey/0dev/galaxy/py3.6.9_dev/config/plugins/tours
galaxy.model.database_heartbeat DEBUG 2019-12-09 21:44:22,063 [p:4196,w:2,m:0] [database_heartbeart_main.web.2.thread] main.web.2 is config watcher
Fatal Python error: Segmentation fault

Current thread 0x000070000dcdf000 (most recent call first):
  File "/Users/sergey/0dev/galaxy/py3.6.9_dev/.venv/lib/python3.6/site-packages/watchdog/observers/fsevents.py", line 138 in run
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x000070000d7dc000 (most recent call first):
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 299 in wait
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/queue.py", line 173 in get
  File "/Users/sergey/0dev/galaxy/py3.6.9_dev/.venv/lib/python3.6/site-packages/watchdog/observers/api.py", line 360 in dispatch_events
  File "/Users/sergey/0dev/galaxy/py3.6.9_dev/.venv/lib/python3.6/site-packages/watchdog/observers/api.py", line 199 in run
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "/Users/sergey/.pyenv/versions/3.6.9/lib/python3.6/threading.py", line 884 in _bootstrap

[... more thread tracebacks here ...]

!!! uWSGI process 4196 got Segmentation Fault !!!
*** backtrace of 4196 ***
0   pyuwsgi.cpython-36m-darwin.so       0x0000000103f1fecc uwsgi_backtrace + 44
1   pyuwsgi.cpython-36m-darwin.so       0x0000000103f20403 uwsgi_segfault + 51
2   libsystem_platform.dylib            0x00007fff741e5b5d _sigtramp + 29
3   ???                                 0x000000010c379b76 0x0 + 4499938166
4   libsystem_c.dylib                   0x00007fff74052d8a raise + 26
5   libsystem_platform.dylib            0x00007fff741e5b5d _sigtramp + 29
6   ???                                 0x00007f99b91f7a00 0x0 + 140298212571648
7   CoreFoundation                      0x00007fff480ce5aa __CFRunLoopFindMode + 687
8   CoreFoundation                      0x00007fff480ce28c __CFRunLoopCreate + 445
9   CoreFoundation                      0x00007fff480cdfe7 _CFRunLoopGet0 + 98
10  _watchdog_fsevents.cpython-36m-darwin.so 0x00000001189616dc watchdog_add_watch + 508
11  python                              0x00000001039266b6 _PyCFunction_FastCallDict + 166
12  python                              0x00000001039b6dc8 call_function + 584
13  python                              0x00000001039b3cf2 _PyEval_EvalFrameDefault + 25122
14  python                              0x00000001039b8219 fast_function + 553
15  python                              0x00000001039b6d99 call_function + 537
16  python                              0x00000001039b3cf2 _PyEval_EvalFrameDefault + 25122
17  python                              0x00000001039b8219 fast_function + 553
18  python                              0x00000001039b6d99 call_function + 537
19  python                              0x00000001039b3cf2 _PyEval_EvalFrameDefault + 25122
20  python                              0x00000001039b86c8 _PyFunction_FastCallDict + 968
21  python                              0x00000001038d8ee6 _PyObject_FastCallDict + 182
22  python                              0x00000001038d9063 _PyObject_Call_Prepend + 131
23  python                              0x00000001038d8d25 PyObject_Call + 101
24  python                              0x0000000103a06366 t_bootstrap + 70
25  python                              0x00000001039fed79 pythread_wrapper + 25
26  libsystem_pthread.dylib             0x00007fff741ee2eb _pthread_body + 126
27  libsystem_pthread.dylib             0x00007fff741f1249 _pthread_start + 66
28  libsystem_pthread.dylib             0x00007fff741ed40d thread_start + 13
*** end of backtrace ***
```

What I've found so far:
This is *not* inherent to the uwsgi+watchdog+mac combination. To verify this, I made a barebones uwsgi app that uses watchdog. It works on both Linux and Mac OS (same uwsgi settings as above): https://github.com/ic4f/watcher_debug/blob/linux/app-watcher.py

I then tried a similar setup in Galaxy: I added a function to `app.py` that started an observer:

```python
def watch():
    event_handler = MyFileSystemEventHandler()
    observer = Observer()
    observer.schedule(event_handler, PATH, recursive=True)
    observer.start()

class MyFileSystemEventHandler(FileSystemEventHandler): 
    def on_modified(self, event):
        print('...')
```

I tried using the uwsgi `@postfork` decorator (on `watch()`), and calling `register.postself.application_stack.register_postfork_function(launch_thread_watcher)`
from UniverseApplication's constructor. Both had the same result:
- same segfault happens; but:
- if `watch()` is also called from UniverseApplication, then: no segfault happens, the master and all the worker processes invoke `watch`, but the event is handled only on the master.

Before I turn this bug into my mission in life, I thought I'd ask for help. I must be missing something obvious here...

Ping @natefoo @mvdbeek 
If this doesn't have an obvious solution, I could use some pointers...

**Comment by mvdbeek** [comment]
Can't reproduce this, is `enable_threads` and `thunder_lock` set to true ? Can you post your `uwsgi:` section ?

**Comment by mvdbeek** [comment]
fwiw this is my uwsgi section:
```
uwsgi:
  buffer-size: 16384
  die-on-term: true
  enable-threads: true
  farm: job-handlers:1
  hook-master-start: unix_signal:15 gracefully_kill_them_all
  http: 127.0.0.1:8080
  manage-script-name: true
  master: true
  module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
  mule: lib/galaxy/main.py
  offload-threads: 1
  processes: 4
  py-call-osafterfork: true
  pythonpath: lib
  threads: 4
  thunder-lock: true
```

**Comment by dannon** [comment]
My config that surfaced the issue originally is:

```
  uwsgi:
    http: 0.0.0.0:8080;
    buffer-size: 16384
    processes: 4
    threads: 4
    offload-threads: 2
    static-map: /static/style=static/style/blue
    static-map: /static=static
    master: false
    virtualenv: .venv
    pythonpath: lib
    mount: /galaxy/blah=galaxy.webapps.galaxy.buildapp:uwsgi_app()
    manage-script-name: true
    thunder-lock: true
    die-on-term: true
    hook-master-start: unix_signal:2 gracefully_kill_them_all
    hook-master-start: unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
```

Probably a silly question, but you did set `watch_tours` or some other watcher to true, right?
