### ISSUE TITLE
Adding health checks accessible via API

### ISSUE THREAD

**Issue by luke-c-sargent** [galaxyproject/galaxy#9180]
hello,

**tl;dr**: i want to add a health check API endpoint; what is the best way to determine if web/job handlers are performing as desired, and how verbose should this output be?

-------

i would like to add health check functionality to Galaxy for web and job handlers, and was looking to implement something similar to what is described in [this IETF proposal draft](https://inadarei.github.io/rfc-healthcheck/), whose schema could look like this:
```
status: <pass/fail/warn>
notes: "..."
checks:
  - web: 
    - componentId: <id>
      componentType: webhandler
      status: <pass/fail/warn>
      notes: "..."
    - <..other web handlers..>
  - job:
    - componentId: <id>
      componentType: jobhandler
      status: <pass/fail/warn>
      notes: "..."
    - <..other job handlers..>
```
roughly, we get an overall status, and further details are provided in the 'checks' field, which contains a list of responses from individual systems. these checks can be more (or less) granular as desired.

this effort was started for kubernetes reasons (readiness / liveness probes) but could be broadly useful to sysadmins or extra-nerdy users curious about server status. 

my naive approach has been to check the `app` member of the `trans` object:
  - for web: check `application_stack.workers()`, iterate through, accept idle or busy status.
  - for job: check `job_manager.job_handler.dispatcher.job_runners`, ensure there are workers associated with it (`nworkers` > 0)

i am sure there are many caveats and oversights in the above (e.g., many runner/handler types), so i would love to hear from my learned colleagues. thanks for reading!
