### ISSUE TITLE
Running Interactive Tools on a (remote) Kubernetes Cluster

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#9448]
https://github.com/galaxyproject/galaxy/pull/8758 was some initial work on this but it required Galaxy itself to be inside the Kubernetes environment. This made writing a test case impossible with given frameworks and it would be unworkable for usegalaxy.org in the medium term.

Our plan for deploying ITs on usegalaxy.org is to run the jobs using Kubernetes staging with Pulsar on a Kubernetes cluster ***remote*** to the Galaxy instance. It would be simpler and faster to simply use #9349 but we decided Kubernetes aligns better with our longer strategic goals and would be essential for cloud offerings.

Implementing this will also make testing the approach within the current github actions pykube framework possible. I think this approach is feasible if we deploy a pod with Nate's double proxy (https://github.com/usegalaxy-eu/gie-nodejs-proxy/pull/2) inside the Kubernetes cluster along with a proxy outside the container beside Galaxy.

Smaller Tasks:
- [x] Merge the double proxy back into the proxy code - perhaps a different entry point for ITs and IEs so they can co-exist. https://github.com/usegalaxy-eu/gie-nodejs-proxy/pull/2
- [x] Update the existing ITs tests to also test with the NodeJS proxy (they currently use the uwsgi proxy).
   - [ ] Merge the code back into Galaxy or reference the external repo somehow?
- [x] Create a pod specification (?) for ITs that will setup the second of the two proxies inside a Kubernetes cluster. Launch as part of Galaxy integration testing.
- [ ] Finish out https://github.com/galaxyproject/galaxy/pull/8758 to get the internal IP address of the container inside the Galaxy database for the outer proxy to consume.
- [ ] Fix up the tests - but everything should just work at that point.
- [ ] Implement SSL keys to secure outer to inner proxy communication.
- [ ] Deploy to test.galaxyproject.org:
   - [ ] Jetstream Kuberentes cluster.
   - [ ] Service with inner proxy.
   - [ ] Outer proxy and job configuration.

This issue replaces https://github.com/galaxyproject/galaxy/pull/8758 and https://github.com/galaxyproject/galaxy/issues/5275.

**Comment by jmchilton** [comment]
- gx-it-proxy published a npm package and docker image. 
- Script that deploys an IT proxy a K8S service and simulates IT container job and external request https://github.com/galaxyproject/gx-it-proxy/commit/b785e23558898040e7ff5ab0daf524106ba4fc29

**Comment by jmchilton** [comment]
Tracking this here - failed work on getting uwsgi to act as the outer proxy. Can't get that header set with httpdumb it seems.

```
PROXY_TO_PROXY_TEMPLATE = string.Template(r"""
uwsgi:
  http-raw-body: true
  interactivetools_map: $tempdir/interactivetools_map.sqlite
  python-raw: scripts/interactivetools/key_type_token_mapping.py
  # if interactive tool path, jump to interactive tool, else skip to
  # endendend (default uwsgi params).
  route-host: ^([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)-([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\.([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\.(interactivetool\.$test_host:$test_port)$ goto:interactivetool
  route-run: goto:endendend

  route-label: interactivetool  
  route-host: ^([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)-([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\.([A-Za-z0-9]+(?:-[A-Za-z0-9]+)*)\.(interactivetool\.$test_host:$test_port)$ rpcvar:TARGET_HOST rtt_key_type_token_mapper_cached $1 $3 $2 $4 $0 5
  route-run: addheader:x-interactive-tool-host:${TARGET_HOST}
  route-if-not: empty:${TARGET_HOST} httpdumb:$remote_proxy
  route: .* break:404 Not Found
  #  
  route-label: endendend
""") 
```
